const ShopActionTypes = {
    FETCH__COLLECTIONS_START: 'FETCH__COLLECTIONS_START',
    FETCH__COLLECTIONS_SUCCESS: 'FETCH__COLLECTIONS_SUCCESS',
    FETCH__COLLECTIONS_FAILURE: 'FETCH__COLLECTIONS_FAILURE'
};

export default ShopActionTypes;